#!/bin/sh
# POSTINST script for InfluxDBWindSVG

echo "\033[36m HI I'M A POSTINST SCRIPT `date +"%s"` \033[39m"
mkdir --parents /var/cache/InfluxDBWindSVG/
systemctl daemon-reload
systemctl enable influxdbwindsvg.service
systemctl start influxdbwindsvg.service

exit 0
